=== miricmilos-Ist/IST-Vezba3/zadatak6/fakultet.dtd
<!ELEMENT fakultet (student*)>
<!ELEMENT student (osoba,upisi+)>
<!--Atributi studenta-->
<!ATTLIST student status (studira|diplomirao) #REQUIRED>
<!ATTLIST student indeks ID #REQUIRED>

<!ELEMENT upisi (semestar+)>
<!ELEMENT semestar (#PCDATA)>
<!--Atributi semestra-->
<!ATTLIST semestar broj CDATA #REQUIRED>
<!ATTLIST semestar godina CDATA #REQUIRED>
<!ATTLIST semestar vrsta (budzet|saf) #REQUIRED>

<!ELEMENT osoba (ime,prezime,mestoRodjenja,datumRodjenja)>
<!ELEMENT ime (#PCDATA)>
<!ELEMENT prezime (#PCDATA)>
<!ELEMENT mestoRodjenja (#PCDATA)>
<!ELEMENT datumRodjenja (#PCDATA)>

=== miricmilos-Ist/IST-Vezba3/zadatak6/fakultet.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fakultet SYSTEM "fakultet.dtd">
<fakultet>
  <student status="studira" indeks="RT6917">
    <osoba>
      <ime>Milos</ime>
      <prezime>Miric</prezime>
      <mestoRodjenja>Kumodraz</mestoRodjenja>
      <datumRodjenja>5/3/1998</datumRodjenja>      
    </osoba>
    <upisi>
      <semestar broj="6" godina="3" vrsta="budzet"></semestar>
    </upisi>
    <upisi>
      <semestar broj="5" godina="2" vrsta="saf"></semestar>
    </upisi>
  </student>
  <student status="diplomirao" indeks="RT3417">
    <osoba>
      <ime>Petar</ime>
      <prezime>Petrovic</prezime>
      <mestoRodjenja>Konjarnik</mestoRodjenja>
      <datumRodjenja>3/2/1998</datumRodjenja>
    </osoba>
    <upisi>
      <semestar broj="4" godina="4" vrsta="saf"></semestar>
    </upisi>
    <upisi>
      <semestar broj="5" godina="2" vrsta="budzet"></semestar>
    </upisi>
    <upisi>
      <semestar broj="2" godina="1" vrsta="saf"></semestar>
    </upisi>
  </student>
</fakultet>
