=== miricmilos-Ist/IST-Vezba3/autooglas (zadatak 2 i 4)/autooglas.dtd
<!--Korenski element-->
<!ELEMENT autoOglas (automobil+)>
<!ELEMENT automobil (proizvodjac, model, godiste, farba, zapremina, transmisija, gorivo, cena, kontakt)>
<!ELEMENT proizvodjac (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ATTLIST model tip CDATA #IMPLIED>
<!ELEMENT godiste (#PCDATA)>
<!ELEMENT farba (#PCDATA)>
<!ATTLIST farba tip (akril|metalik) #REQUIRED>
<!ELEMENT zapremina (#PCDATA)>
<!ATTLIST zapremina mera (ccm|I) #REQUIRED>
<!ELEMENT transmisija (#PCDATA)>
<!ATTLIST transmisija tip (auto|manual) #REQUIRED>
<!ELEMENT gorivo (#PCDATA)>
<!ATTLIST gorivo tng (da|ne) #IMPLIED>
<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena valuta (din|eur) #REQUIRED>
<!ELEMENT kontakt (#PCDATA)>

=== miricmilos-Ist/IST-Vezba3/autooglas zadatak/autooglas.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE autoOglas SYSTEM "autooglas.dtd">
<!-- Koren -->
<!-- Proverena validnost na https://www.xmlvalidation.com -->
<autoOglas>
  <automobil>
    <proizvodjac>Audi</proizvodjac>
    <model tip="limuzina">R8</model>
    <godiste>2010</godiste>
    <farba tip="metalik">Crna</farba>
    <zapremina mera="cm^3">3000</zapremina>
    <transimisija tip="manual">6</transimisija>
    <gorivo tng="da">Dizel</gorivo>
    <cena valuta="EUR">200000</cena>
    <kontakt>+381656251425</kontakt>
  </automobil>
</autoOglas>
