=== miricmilos-Ist/IST-Vezba3/zadatak5/newspaper.dtd
<!ELEMENT newspaper (article+)>
<!ELEMENT article (headline, byline, lead, body, notes)>

<!--article atributi-->
<!ATTLIST article author CDATA #REQUIRED>
<!ATTLIST article editor CDATA #IMPLIED>
<!ATTLIST article date CDATA #IMPLIED>
<!ATTLIST article edition CDATA #IMPLIED>
<!--kraj atributa-->

<!ELEMENT headline (#PCDATA)>
<!ELEMENT byline (#PCDATA)>
<!ELEMENT lead (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

<!--promenljive-->
<!ENTITY newspaper "nytimes">
<!ENTITY publisher "ENPA">
<!ENTITY copyright "Copyright NY Times">

=== miricmilos-Ist/IST-Vezba3/zadatak5/newspaper.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE newspaper SYSTEM "newspaper.dtd">
<newspaper>
  <!--Validacija prosla bez gresaka-->
  <article author="Aleksandar Tirnanic" editor="Blagoje Marijanovic">
    <headline>Srbija osvojila drugo mesto na prvom svetskom prvenstvu u fudbalu</headline>
    <byline>Aleksandar</byline>
    <lead>Otvarajuci paragraf</lead>
    <body>Dugacak tekst</body>
    <notes>&newspaper;&newspaper;&copyright;</notes>    
  </article>
  <article author="Dragan Bjelogrlic" date="31/3/2020">
    <headline>Senke Nad Balkanom obara rekorde gledanosti</headline>
    <byline>Dragan</byline>
    <lead>Otvarajuci paragraf</lead>
    <body>Dugacak tekst</body>
    <notes>&newspaper;&newspaper;&copyright;</notes>
  </article>
  <article author="Milos Avramovic" edition="prvo">
    <headline>Vuk Kostic se pridruzuje glumackoj ekipi u seriji Juzni Vetar</headline>
    <byline>Avramovic</byline>
    <lead>Otvarajuci paragraf</lead>
    <body>Dugacak tekst</body>
    <notes>&newspaper;&newspaper;&copyright;</notes>
  </article>
</newspaper>
